# get this into plate2N
#

utils::globalVariables(c("plate_id", "slope", "adj_r_squared", "lm_p", "dataset", "map", "abs_corrected", "std_sp", "std_unit"))

#' Merge Data from Regression Equation on Standard Curve with Absorbance Data (samples)
#'
#' @param lm_table A tibble with linear model data (as generated by `lm_std_curve()`).
#'     Must contain columns `plate_id`, `slope`, `adj_r_squared`, `lm_p`
#' @param abs_data Blank-corrected absorbance data, in a similar format to tidy_plates,
#'     but containing only sample wells, no empty wells, standard curve wells or extractant wells
#' @param target_sp Defaults to "N", the target compound to convert to
#'
#' @returns A tibble joining linear model data with absorbance data
#' @export
#'
#' @examples
#' lm_table <- lm_output$lm_data
#' sample_data <- sample_corrected
#' reg_join_abs(lm_table, sample_data, target_sp = "N")
reg_join_abs <- function(
    lm_table,
    abs_data,
    target_sp = "N"
) {
  reg_data <- lm_table |>
    dplyr::select(plate_id, slope, adj_r_squared, lm_p)

  joined_data <- abs_data |>
    dplyr::select(dataset, plate_id, map, abs_corrected, std_sp, std_unit) |>
    dplyr::left_join(reg_data, by = dplyr::join_by(plate_id)) |>
    dplyr::mutate(target_sp = rep(target_sp), .after = std_sp)

  return(joined_data)
}




utils::globalVariables(c("molar_masses", "std_sp", "target_sp", "conc_mgNsp_L"))

#' Converts Concentrations From Compound Weight to Target Weight
#'
#' Convert units of concentrations from "mg Compound L-1" to "mg Target L-1". This
#'     allows, for example, to convert concentrations expressed in mg NH4 / L to
#'     mg N / L. This conversion requires a vector where molar masses of both
#'     Compound and Target are stored. This function works in bulk, on a tibble
#' Target (e.g., nitrogen) will be expressed in the same unit as the compound
#'     (origin, e.g. NH4). For example, we go from "mg NH4 / L" to "mg N / L".
#'     We don't go from mg to g or kg...
#'
#' @param conc_data A tibble containing columns "std_sp" (chr), "target_sp" (chr),
#'     "conc_mgNsp_L" (dbl). Columns "target_sp" means "to convert to" (e.g., "N" for mg N / L),
#'     and "std_sp" means "to convert from" (e.g., "NH4" for mg NH4 / L)
#' @param masses A named vector of molar masses (names of the elements = compounds.)
#'
#' @returns A tibble of the same format, with an added column. For now, this new column
#'     is named `conc_mgN_L". But we could consider adding an argument to define column names
#'
#' @seealso molar_masses
#'
#' @export
#'
#' @examples
#' tidy_plates
#' molar_masses
convert_molec <- function(
    conc_data,
    masses = molar_masses
) {
  # extract all combinations of std_sp and target_sp
  combos <- conc_data |> dplyr::select(std_sp, target_sp) |> unique()

  # initialize an empty tibble with the right structure
  target_data <- conc_data |> dplyr::filter_out() |> dplyr::mutate(conc_mgN_L = double())
  # Loop, once per combination of std-sp / target-sp
  #i = 1
  for (i in 1:nrow(combos)) {

    # get which compound and which target, and their molar masses
    comp_i <- combos$std_sp[i] ; M_comp <- molar_masses[comp_i]
    target_i <- combos$target_sp[i] ; M_target <- molar_masses[target_i]

    data_i <-
      conc_data |>
      # select subset corresponding to combos[i]
      dplyr::filter(std_sp == comp_i, target_sp == target_i) |>
      # compute convertion
      dplyr::mutate(conc_mgN_L = conc_mgNsp_L * M_target / M_comp)

    # append the new tibble
    target_data <- target_data |> dplyr::bind_rows(data_i)
  }

  return(target_data)

}
