
#' Merge Data from Regression Equation on Standard Curve with Absorbance Data (samples)
#'
#' @param lm_table A tibble with linear model data (as generated by `lm_std_curve()`).
#'     Must contain columns `plate_id`, `slope`, `adj_r_squared`, `lm_p` (linear
#'     model) or `plate_id`, `poly_a`, `poly_a_p`, `poly_b`, `poly_b_p`,
#'     `r_squared`, `adj_r_squared`, `lm_p` (polynomial model)
#' @param abs_data Blank-corrected absorbance data, in a similar format to tidy_plates,
#'     but containing only sample wells, no empty wells, standard curve wells or extractant wells
#' @param target_sp Defaults to "N", the target compound to convert to
#' @param plate_id_col Name of the column identifying physical plates.
#'     Defaults to `"plate_id"`.
#' @param dataset_col Name of the column identifying the dataset. Defaults
#'     to `"dataset"`.
#' @param map_col Name of the column containing well mapping/type
#'     information. Defaults to `"map"`.
#' @param well_id_col Name of the column identifying wells. Defaults to
#'     `"well_id"`.
#' @param value_col Name of the column containing (blank-corrected)
#'     absorbance. Defaults to `"abs_corrected"`.
#' @param std_sp_col Name of the column identifying the standard species.
#'     Defaults to `"std_sp"`.
#' @param unit_col Name of the column containing the concentration unit.
#'     Defaults to `"std_unit"`.
#'
#' @returns A tibble joining linear model data with absorbance data
#' @export
#'
#' @examples
#' lm_table <- lm_output$lm_data
#' sample_data <- sample_corrected
#' reg_join_abs(lm_table, sample_data, target_sp = "N")
reg_join_abs <- function(
    lm_table,
    abs_data,
    target_sp = "N",
    plate_id_col = "plate_id",
    dataset_col = "dataset",
    map_col = "map",
    well_id_col = "well_id",
    value_col = "abs_corrected",
    std_sp_col = "std_sp",
    unit_col = "std_unit"
) {
  if ("slope" %in% names(lm_table)) {
    reg_data <- lm_table |>
      dplyr::select(dplyr::all_of(c(plate_id_col, "slope", "adj_r_squared", "lm_p")))
  } else if ("poly_a" %in% names(lm_table)) {
    reg_data <- lm_table |>
      dplyr::select(dplyr::all_of(c(
        plate_id_col, "poly_a", "poly_a_p", "poly_b", "poly_b_p",
        "r_squared", "adj_r_squared", "lm_p")))
  } else stop("Required column names are missing. See `?reg_join_abs()`")

  joined_data <- abs_data |>
    dplyr::select(dplyr::all_of(c(
      dataset_col, plate_id_col, map_col, well_id_col, value_col, std_sp_col, unit_col))) |>
    dplyr::left_join(reg_data, by = plate_id_col) |>
    dplyr::mutate(target_sp = target_sp, .after = dplyr::all_of(std_sp_col))

  return(joined_data)
}


utils::globalVariables("molar_masses")
#' Converts Concentrations From Compound Weight to Target Weight
#'
#' Convert units of concentrations from "mg Compound L-1" to "mg Target L-1". This
#'     allows, for example, to convert concentrations expressed in mg NH4 / L to
#'     mg N / L. This conversion requires a vector where molar masses of both
#'     Compound and Target are stored. This function works in bulk, on a tibble
#' Target (e.g., nitrogen) will be expressed in the same unit as the compound
#'     (origin, e.g. NH4). For example, we go from "mg NH4 / L" to "mg N / L".
#'     We don't go from mg to g or kg...
#'
#' @param conc_data A tibble containing the columns referenced by
#'     `std_sp_col`, `target_sp_col`, and `value_col`.
#' @param masses A named vector of molar masses (names of the elements = compounds.)
#' @param std_sp_col Name of the column identifying which compound to
#'     convert FROM (e.g. "NH4" for mg NH4 / L). Defaults to `"std_sp"`.
#' @param target_sp_col Name of the column identifying which compound to
#'     convert TO (e.g. "N" for mg N / L). Defaults to `"target_sp"`.
#' @param value_col Name of the column containing the concentration to
#'     convert. Defaults to `"conc_mgNsp_L"`.
#' @param output_col Name of the new column holding the converted
#'     concentration. Defaults to `"conc_mgN_L"`.
#'
#' @returns A tibble of the same format, with the converted concentration
#'     added as a new column (see `output_col`).
#'
#' @seealso molar_masses
#'
#' @export
#'
#' @examples
#' molar_masses
#'
#' # small example: convert mg NH4/L to mg N/L
#' conc_data <- tibble::tibble(
#'   plate_id = c("P01", "P02"),
#'   std_sp = c("NH4", "NH4"),
#'   target_sp = c("N", "N"),
#'   conc_mgNsp_L = c(5.2, 3.8)
#' )
#' convert_molec(conc_data)
convert_molec <- function(
    conc_data,
    masses = molar_masses,
    std_sp_col = "std_sp",
    target_sp_col = "target_sp",
    value_col = "conc_mgNsp_L",
    output_col = "conc_mgN_L"
) {
  # extract all combinations of std_sp and target_sp
  combos <- conc_data |> dplyr::select(dplyr::all_of(c(std_sp_col, target_sp_col))) |> unique()

  target_data <- NULL
  for (i in seq_len(nrow(combos))) {
    # get which compound and which target, and their molar masses -
    # from the masses argument, not the hardcoded molar_masses dataset
    comp_i <- combos[[std_sp_col]][i]; M_comp <- masses[comp_i]
    target_i <- combos[[target_sp_col]][i]; M_target <- masses[target_i]

    data_i <-
      conc_data |>
      dplyr::filter(.data[[std_sp_col]] == comp_i, .data[[target_sp_col]] == target_i) |>
      dplyr::mutate("{output_col}" := .data[[value_col]] * M_target / M_comp)

    target_data <- dplyr::bind_rows(target_data, data_i)
  }
  return(target_data)
}
