#' Example of a tibble format for plate data
#'
#' This particular tibble was generated with the `csv_to_tibble()`function, but the end structure is strictly the same with all import options (e.g., with `skanit_to_tibble()`or `txt_to_tibble()`). It contains practise "plate data" to be used within the `plate2N`package. A tibble (data frame) with 96-well plate data in a plate format (data can be numerical, e.g., for absorbance data, or characters, e.g., for mapping data).
#'
#' @format
#' A tibble with 13 columns and 9 rows per plate, with no empty rows:
#' \describe{
#'  \item{row}{column with an iterative structure every 9 rows. The first row of this column contains the plate id, the next 8 rows contain letters from A to H, reflecting plate rows}
#'  \item{X1:X12}{containing data from the 12 columns of each plate, where the first row of each plate mentions plate-column number, from 1 to 12}
#' }
#'
#'
"tibble_example"


#' Example of the verticalized plate data
#'
#' This data set was generated by the [`verticalize_plates()`] function, ran on our example data set [`tibble_example`].
#'
#' @format
#' A tibble with 96 rows (1 per well of the 96-well plate) and 6 columns
#' \describe{
#'  \item{row}{1-letter identifier of the original plate-row (letters A to H)}
#'  \item{column}{1-number identifier of the original plate-column (numbers 1 to 12)}
#'  \item{NO3_TDN_01 to NO3_TDN_04}{each column corresponds to 1 plate of the input tibble and contains verticalized plate data}
#' }
#'
#'
"vertical_plates"

#' Example of Tidy table of plate data
#'
#' This tidy table set was generated from raw data in the skanit format (see the raw file stored at `system.file("extdata", "skanit.csv", package = "plate2N"))`.
#' The data wrangling pipeline followed steps of the vignette (see `vignette("import-tidy, package = "plate2N")`),
#' i.e., data was imported with [`skanit_to_tibble()`], then absorbance and mapping data were verticalized and merged with [`join_abs_map()`],
#' and finally the verticalized plate data was rearranged using [`tidyr::pivot_longer()`] and [`tidyr::pivot_wider()`].
#'
#' The `tidy_table`represents data corresponding to 5 physical 96-well plates, where absorbance and mapping data are merged (thus containing 10 times the volume of data of 1 plate).
#'
#' @format
#' A tibble with 960 rows (1 per well of the 5x2 data plates) and 8 columns
#' \describe{
#'  \item{row}{1-letter identifier of the original plate-row (letters A to H)}
#'  \item{column}{1-number identifier of the original plate-column (numbers 1 to 12)}
#'  \item{well_id}{concatenation of `row` and `column` (values from A1 to H12). Each `well_id` is repeated 10 times (once per data plate)}
#'  \item{plate_id}{Unique identifier for each physical 96-well plate (thus repeated 2x each, corresponding to absorbance and mapping data)}
#'  \item{unique_well_id}{concatenation of `well_id` and `plate_id`, it identifies uniquely every single well}
#'  \item{dataset}{here, all data comes from a single dataset called "expe1", but the information on dataset is added at the merging stage, and could allow filtering the `tidy_table` based on dataset}
#'  \item{map}{mapping data from the 96-well plates. This can contain a sample identifier and/or treatment identifier. It reflects strictly the data that was imported from the raw data files}
#'  \item{abs}{absorbance data from the 96-well plates. This, too, corresponds strictly to the imported data. Note that absorbance data is still stored as a character string. Use [`as.double()`] or [`as.numeric()`] to turn it into numbers}
#' }
#'
"tidy_table"

#' Example of failed well table
#'
#' In experiments with 96-well plates, especially with manual pipetting,
#' it is not rare to have some mishaps where we know that a certain well is to be excluded.
#' A template for such data can be obtained using [`failed_wells_template()`],
#' exported (e.g., with [`readr::write_csv()`]) filled by users and imported (e.g., with [`readr::read_csv()`]).
#'
#' @format
#' A tibble 2 rows and 3 columns (dataset, plate_id and well_id), allowing unique identification of failed wells
#' \describe{
#'  \item{dataset,plate_id}{must be the same as in your plate data}
#'  \item{well_id}{standard well identifiers, concatenation of plate rows (letters from A to H) and plate columns (numbers from 1 to 12)}
#' }
#'
"failed_wells_example"

