#' Example of a tibble format for plate data
#'
#' This particular tibble was generated with the `csv_to_tibble()`function, but the end structure is strictly the same with all import options (e.g., with `skanit_to_tibble()`or `txt_to_tibble()`). It contains practise "plate data" to be used within the `plate2N`package. A tibble (data frame) with 96-well plate data in a plate format (data can be numerical, e.g., for absorbance data, or characters, e.g., for mapping data).
#'
#' @format
#' A tibble with 13 columns and 9 rows per plate, with no empty rows:
#' \describe{
#'  \item{row}{column with an iterative structure every 9 rows. The first row of this column contains the plate id, the next 8 rows contain letters from A to H, reflecting plate rows}
#'  \item{X1:X12}{containing data from the 12 columns of each plate, where the first row of each plate mentions plate-column number, from 1 to 12}
#' }
#'
#'
"tibble_example"

#' Example of the tidy, verticalized plate data
#'
#' This data set was generated by the `verticalize_plates()`function, ran on our example data set `tibble_example`.
#'
#' @format
#' A tibble with 96 rows (1 per well of the 96-well plate) and 6 columns
#' \describe{
#'  \item{row}{1-letter identifier of the original plate-row (letters A to H)}
#'  \item{column}{1-number identifier of the original plate-column (numbers 1 to 12)}
#'  \item{NO3_TDN_01 to NO3_TDN_04}{each column corresponds to 1 plate of the input tibble and contains verticalized plate data}
#' }
#'
#'
"vertical_plates"
