#' Example of a tibble format for plate data
#'
#' This particular tibble was generated with the `csv_to_tibble()`function, but the end structure is strictly the same with all import options (e.g., with `skanit_to_tibble()`or `txt_to_tibble()`). It contains practise "plate data" to be used within the `plate2N`package. A tibble (data frame) with 96-well plate data in a plate format (data can be numerical, e.g., for absorbance data, or characters, e.g., for mapping data).
#'
#' @format
#' A tibble with 13 columns and 9 rows per plate, with no empty rows:
#' \describe{
#'  \item{row}{column with an iterative structure every 9 rows. The first row of this column contains the plate id, the next 8 rows contain letters from A to H, reflecting plate rows}
#'  \item{X1:X12}{containing data from the 12 columns of each plate, where the first row of each plate mentions plate-column number, from 1 to 12}
#' }
#'
#'
"tibble_example"


#' Example of the verticalized plate data
#'
#' This data set was generated by the [`verticalize_plates()`] function, ran on our example data set [`tibble_example`].
#'
#' @format
#' A tibble with 96 rows (1 per well of the 96-well plate) and 6 columns
#' \describe{
#'  \item{row}{1-letter identifier of the original plate-row (letters A to H)}
#'  \item{column}{1-number identifier of the original plate-column (numbers 1 to 12)}
#'  \item{NO3_TDN_01 to NO3_TDN_04}{each column corresponds to 1 plate of the input tibble and contains verticalized plate data}
#' }
#'
#'
"vertical_plates"

#' Example of Tidy table of plate data
#'
#' This tidy table set was generated from raw data in the skanit format (see the raw file stored at `system.file("extdata", "skanit.csv", package = "plate2N"))`.
#' The data wrangling pipeline followed steps of the vignette (see `vignette("import-tidy, package = "plate2N")`),
#' i.e., data was imported with [`skanit_to_tibble()`], then absorbance and mapping data were verticalized and merged with [`join_abs_map()`],
#' and finally the verticalized plate data was rearranged using [`tidyr::pivot_longer()`] and [`tidyr::pivot_wider()`].
#'
#' The `tidy_table`represents data corresponding to 5 physical 96-well plates, where absorbance and mapping data are merged (thus containing 10 times the volume of data of 1 plate).
#'
#' @format
#' A tibble with 960 rows (1 per well of the 5x2 data plates) and 8 columns
#' \describe{
#'  \item{row}{1-letter identifier of the original plate-row (letters A to H)}
#'  \item{column}{1-number identifier of the original plate-column (numbers 1 to 12)}
#'  \item{well_id}{concatenation of `row` and `column` (values from A1 to H12). Each `well_id` is repeated 10 times (once per data plate)}
#'  \item{plate_id}{Unique identifier for each physical 96-well plate (thus repeated 2x each, corresponding to absorbance and mapping data)}
#'  \item{unique_well_id}{concatenation of `well_id` and `plate_id`, it identifies uniquely every single well}
#'  \item{dataset}{here, all data comes from a single dataset called "expe1", but the information on dataset is added at the merging stage, and could allow filtering the `tidy_table` based on dataset}
#'  \item{map}{mapping data from the 96-well plates. This can contain a sample identifier and/or treatment identifier. It reflects strictly the data that was imported from the raw data files}
#'  \item{abs}{absorbance data from the 96-well plates. This, too, corresponds strictly to the imported data. Note that absorbance data is still stored as a character string. Use [`as.double()`] or [`as.numeric()`] to turn it into numbers}
#' }
#'
"tidy_table"

#' Example of Tidy table of plate data
#'
#' The `tidy_table`represents data corresponding to 5 physical 96-well plates,
#' where absorbance and mapping data are merged (thus containing 10 times the volume of data of 1 plate).
#'
#' This tidy table set was generated from raw absorbance data in the .TXT format,
#' (see the raw file stored at `system.file("extdata", "txt_examples", package = "plate2N")`).
#' The mapping data was imported from a .csv format, (see also the raw file stored at
#' `system.file("extdata", "csv_map.csv", package = "plate2N")`)
#'
#' The data wrangling pipeline followed steps of the vignette (see `vignette("import-tidy, package = "plate2N")`),
#' i.e., data was imported with [`txt_to_tibble()`] and [`csv_to_tibble()`], then absorbance and mapping data were verticalized and merged with [`join_abs_map()`],
#' and finally the verticalized plate data was rearranged using [`vertical_to_tidy()`].
#'
#' @format
#' A tibble with 960 rows (1 per well of the 5x2 data plates) and 8 columns
#' \describe{
#'  \item{row}{1-letter identifier of the original plate-row (letters A to H)}
#'  \item{column}{1-number identifier of the original plate-column (numbers 1 to 12)}
#'  \item{well_id}{concatenation of `row` and `column` (values from A1 to H12). Each `well_id` is repeated 10 times (once per data plate)}
#'  \item{plate_id}{Unique identifier for each physical 96-well plate (thus repeated 2x each, corresponding to absorbance and mapping data)}
#'  \item{unique_well_id}{concatenation of `well_id` and `plate_id`, it identifies uniquely every single well}
#'  \item{dataset}{here, all data comes from a single dataset called "expe1", but the information on dataset is added at the merging stage, and could allow filtering the `tidy_table` based on dataset}
#'  \item{map}{mapping data from the 96-well plates. This can contain a sample identifier and/or treatment identifier. It reflects strictly the data that was imported from the raw data files}
#'  \item{abs}{absorbance data from the 96-well plates. This, too, corresponds strictly to the imported data. Note that absorbance data is still stored as a character string. Use [`as.double()`] or [`as.numeric()`] to turn it into numbers}
#' }
#'
"tidy_plates"

#' Example of failed well table
#'
#' In experiments with 96-well plates, especially with manual pipetting,
#' it is not rare to have some mishaps where we know that a certain well is to be excluded.
#' A template for such data can be obtained using [`failed_wells_template()`],
#' exported (e.g., with [`readr::write_csv()`]) filled by users and imported (e.g., with [`readr::read_csv()`]).
#'
#' @format
#' A tibble 2 rows and 3 columns (dataset, plate_id and well_id), allowing unique identification of failed wells
#' \describe{
#'  \item{dataset,plate_id}{must be the same as in your plate data}
#'  \item{well_id}{standard well identifiers, concatenation of plate rows (letters from A to H) and plate columns (numbers from 1 to 12)}
#' }
#'
"failed_wells_example"

#' Example of plate metadata
#'
#' Must-have columns are those detailed here.
#'
#' Additional recommended columns are those recording detail on extractant.
#'    This is information that can easily get lost, and is especially relevant when
#'    there are variations within a lab (ex., K2SO4 vs KCl, or extractant concentration, ...).
#'    Here, we propose to record extractant species (K2SO4), extractant unit (M) and extractant concentration (0.5).
#'
#' More experimental parameters could be relevant as well (e.g., dilution, incubation time,
#'    sampling time, researcher, machine used, wavelength,...)
#'
#' Recording date and time can help to distinguish batch-effects
#'
#' @format
#' A tibble with 1 row per plate, and an indefinite number of columns
#' \describe{
#'  \item{dataset,plate_id}{must be the same as in your plate data (dataset manually encoded in the import-tidy pipeline)}
#'  \item{std_sp, std_unit, std_conc}{characterize the standard curve. The format of std_conc, with `.`as a digit separator and `-`as a value separator is important. Concentration values MUST be in ascending order}
#' }
#'
"metadata"

#' Example of Blank-corrected Data for Standard Curve
#'
#' @format
#' A tibble with 1 row per well containing serial dilutions of the standard curve. Most relevant columns are described here
#'
#' \describe{
#'  \item{row, column, well_id, plate_id, dataset}{of the 96-well plate}
#'  \item{unique_curve_id}{relevant when there are several curves per plate}
#'  \item{unique_well_id}{combination of well_id and plate_id}
#'  \item{map}{mapping og the wells ("Std" in this case)}
#'  \item{abs_corrected}{blank-corrected absorbance value. Note that the `abs` column has been removed to avoid inadvertend use of uncorrected data }
#'  \item{map}{mapping og the wells ("Std" in this case)}
#'  \item{map}{mapping og the wells ("Std" in this case)}
#'  \item{std_sp, std_unit, std_conc}{characterize the species, concentration
#'       and unit of the standard solution in that well}
#' }
#'
"std_corrected"



#' Example of Blank-corrected Absorbance Data (samples)
#'
#'
#' @format
#' Tibble in format as generated by `blank_correct_abs()`
#'
#' \describe{
#'  \item{abs_corrected}{blank-corrected absorbance}
#'  \item{other columns}{Same columns as `tidy_plates`, + extractant average}
##' }
#'
"sample_corrected"

#' Example of Outputs from the Linear Model of the Standard Curves
#'
#'
#' @format
#' List containing 3 elements, computed with `lm_std_curve()`, `suspicious_lm()`
#'     and `plot_list_lm()`.
#'
#' \describe{
#'  \item{lm_data}{Tibble, 1 row per curve, serves as summary for the linear model}
#'  \item{suspicious_lm}{Subset of `lm_data`, keeping only "problematic" curves,
#'      i.e., either with p-value > 0.5, or with non-normality or
#'      heteroscedasticity of residuals}
#'  \item{plot_list_suspicious}{A list of ggplots displaying those problematic curves
#'      (only one plot in this data set)}
##' }
#'
"lm_output"


#' Record of molar masses for studied compounds
#'
#' Originally, it contains molar masses of N, NO3-, NO2-, NH4+, but it can easily
#'     be appended with additional molar masses for other relevant applications
#'
#' @format
#' A vector of named numerics containing relevant molar masses.
#'
#' \describe{
#'  \item{N}{molar mass of elemental nitrogen in g/mol (not N2)}
#'  \item{NO3}{molar mass of nitrate in g/mol}
#'  \item{NO2}{molar mass of nitrite in g/mol}
#'  \item{NH4}{molar mass of ammonium in g/mol}
##' }
#'
"molar_masses"


#' Correspondance Table between Plate Mapping and Extractant ID
#'
#' Such a table is only needed in the case where several extractants are found on
#'     a single plate. In this case, we need to allocate to each extractant (e.g,
#'     "extr_1", "extr_2") the samples that need blank-correction from that
#'     extractant. This table could, in theory, be as reduced as 2 columns (one for
#'     mapping or `map`, one for extractant or `extr_id`). However, should the mapping
#'     not be unique (e.g., repeated over several plates), or the extractant bear the
#'     same name across plates, it is prudent to add additional columns to ensure
#'     unequivocal relations between wells and their corresponding blanks, such
#'     as `dataset` and `plate_id`.
#'
#' @format
#' A tibble with one row per well, and the following columns:
#'
#' \describe{
#'  \item{dataset,plate_id}{allowing the unique identification of the 96-well plate}
#'  \item{map}{identifier of samples, Standard curve or extractant (“extr_1" or "extr_2")}
#'  \item{extr_id}{extractant identifier corresponding to each well. 3 possible
#'      values: "extr_1", "extr_2" or "none" (for empty wells or standard curves)}
##' }
#'
"multiple_extractant_id"


