utils::globalVariables(c("std_conc", "abs_corrected"))

#' Compute a list of plots, one per standard curve
#'
#' @param lm_data lm_data in the shape as generated by `lm_std_curve()`,
#'     possibly as a subset to observe only suspicious curves
#' @param std_data tibble containing only standard data, as in `std_corrected`.
#'     Absorbance values should already by blank-corrected
#'
#' @import dplyr ggplot2
#'
#' @returns A list of plots, one per curve, annotated with the issue:
#'     - non-significance of the linear modal (p-value > 0.05)
#'     - non-normality of residuals (shapiro test with threshold of p = 0.05)
#'     - heteroscedasticity of residuals (Breusch-Pagan test, threshold of p = 0.05)
#' @export
#'
#' @examples
#' lm_data <- lm_std_curve(std_corrected |> dplyr::group_by(plate_id, column))
#' plot_list <- plot_list_lm(
#'     lm_data,
#'     std_data = std_corrected)
#' plot_list[[1]] ; plot_list[[2]]
plot_list_lm <- function(
    lm_data,
    std_data) {

  #i = 1
  plots <- list()

  #for (i in 1:10) {
  for (i in 1:nrow(lm_data)) {
    # curve data
    lm_curve <- lm_data[i,]
    curve_id <- lm_data$unique_curve_id[i]

    curve_data <- std_data |>
      dplyr::filter(unique_curve_id == curve_id) |>
      dplyr::mutate(std_conc = as.numeric(std_conc))

    # std unit for plotting
    std_unit <- curve_data$std_unit |> unique()

    # gathering info to display
    if (lm_curve$lm_p < 0.05) { lm_p_msg <- ""} else {
      lm_p_msg <- paste0("non-significant linear model, p_val = ", lm_curve$lm_p)
    }
    if (lm_curve$normality_lm_residuals == "Normal") {norm_msg <- ""} else {
      norm_msg <- "Non-Normality of lm residuals"
    }
    if (lm_curve$homoscedasticity_lm_residuals != "Heteroscedasticity") {
      homosced_msg <- ""} else {
        homosced_msg <- "Heteroscedasticity of lm residuals"
      }

    annotation <- paste(lm_p_msg, norm_msg, homosced_msg)
    x_pos <- min(curve_data$std_conc)
    y_pos <- max(curve_data$abs_corrected)*0.9

    # plot
    plot <- plot_std(curve_data |> dplyr::rename(abs = abs_corrected)) +
      ggplot2::labs(title = curve_id) +
      ggplot2::xlab(paste0("Concentration of Standard Curve [", std_unit, "]")) +
      ggplot2::ylab("Blank-corrected Absorbance") +
      ggplot2::theme(legend.position = "none") +
      ggplot2::annotate(
        geom = "label", label = annotation,
        x = x_pos, y = y_pos, hjust = 0, colour = "red")
    #plot
    plots[[curve_id]] <- plot
    #i = i+1

  }

  return(plots)

}
