
#' Quality check of raw absorbance data for extractant wells
#'
#' Extracts plate ID's where it is suspected that raw absorbance
#'     data for extractant (sample blank) still contain some outliers.
#'     The criterion for a plate to be deemed "suspicious" is defined by max_coeff
#'
#' @param data A tibble, as in `tidy_plates`
#' @param max_coeff User-defined, in % (defaults at 5): determines the threshold
#'     coefficient of variation for raw absorbance of extractant wells, above which
#'     plates will be considered "suspicious"
#' @param suppress_message Logical, whether or not to suppress the "success" message (given when no plate is above the `max_coeff`)
#' @param suppress_warning Logical, whether or not to suppress the warning (given when some plate are above the `max_coeff`)
#'
#' @import dplyr
#' @importFrom magrittr extract2
#' @returns ID's of suspicious plates. (+ a message or warning if not suppressed)
#'
#' @export
#'
#' @examples
#' # example code
#' data <- tidy_plates
#' extractant_average <- tidy_plates |> extractant_average()
#' suspicious_plate_id <- qc_raw_extr(data, max_coeff = 0.5)
qc_raw_extr <- function(
    #extractant_average = NULL, # must be a tibble in format as `extractant_average(tidy_plates)$extr_avg`
    data,
    max_coeff = 5,
    suppress_message = FALSE,
    suppress_warning = FALSE
) {

  # compute extractant average if missing
  #if (is.null(extractant_average)) {
    extractant_average <- extractant_average(data)
 # }

  # if all coefficient of variation below thrsehold --> YAY
  if (max(extractant_average$extr_coeff_var_percent) < max_coeff) {
    if (!suppress_message) {
      message(paste0(
        "Good news: all plates show a satisfactorily small variation ",
        "for raw blank (extractant) absorbance values. ",
        "This means that the coefficient of variation is below the threshold of ",
        max_coeff,
        "%."))
    }

  # ELSE, if threshold is passed
  } else if (max(extractant_average$extr_coeff_var_percent) >= max_coeff)  {

    # store id of problematic plates
    suspicious_plate_id <- extractant_average |>
      dplyr::filter(extr_coeff_var_percent > max_coeff) |>
      dplyr::select(plate_id) |> as.vector() |> magrittr::extract2(1)

    # send a warning
    if (!suppress_warning) {
      warning(paste0(
        "There is a big variation in absorbance values for the blanc (more than ",
        max_coeff,
        "%).
        Remove the most unlikely values / remove outliers manually.
        Suspicious plate ID's are returned"))
    }

    return(suspicious_plate_id)
  }
}


utils::globalVariables(c("map", "abs", "plate_id"))
#' Extract suspicious extractant wells
#'
#' @param data Tibble formatted as `tidy_plates`
#' @param suspicious_plate_id If NULL (default), computed from `data` with `qc_raw_extr(data, max_coeff = max_coeff)`
#' @param max_coeff User-defined threshold value, defaults at 5%. All plates for which
#'     the coefficient of variation for extractant raw absorbance is above this threshold
#'     will be considered "suspicious plates"
#'
#' @import dplyr ggplot2
#' @importFrom patchwork wrap_plots
#' @importFrom patchwork plot_annotation
#'
#' @returns A subset of `data` containing only plates where
#'     raw extractant values should be reviewed
#'
#' @export
#'
#' @examples
#' data <- tidy_plates
#' # 0.5 is unreasonable in most uses, but is used here to ensure some output
#' suspicious_plate_id <- qc_raw_extr(data, max_coeff = 0.5,
#'     suppress_message = TRUE, suppress_warning = TRUE)
#' suspicious_extr <- suspicious_extr(data, max_coeff = 0.5,
#'     suspicious_plate_id = suspicious_plate_id)
#' suspicious_extr
suspicious_extr <- function(
    data,
    suspicious_plate_id = NULL, # suspicious_plate_id <- qc_raw_extr(data)
    max_coeff = 5

) {

  if (is.null(suspicious_plate_id)) {
    suspicious_plate_id <- qc_raw_extr(
      data, max_coeff = max_coeff)
    }

  suspicious_extractant <- extract_extractant(data) |>
    dplyr::group_by(plate_id, map) |>
    dplyr::filter(plate_id %in% suspicious_plate_id) |>
    dplyr::arrange(plate_id) |>
    mutate(abs = as.numeric(abs))

  return(suspicious_extractant)
}



#' Multiple distribution plot to review suspicious extractant values and spot outliers
#'
#' @param suspicious_extractant A tibble as generated by `suspicious_extr()`,
#'     can be computed from `data` with `suspicious_extr()`
#' @param data Defaults to NULL. If provided, must be a tibble formatted as `tidy_plates`
#' @param max_coeff User-defined threshold value, defaults at 5%. All plates for which
#'     the coefficient of variation for extractant raw absorbance is above this threshold
#'     will be considered "suspicious plates". ! Be consistent with previous steps
#'
#' @returns A multiple plot for quality checking of extractant wells distribution
#'     and definition of threshold values
#' @export
#'
#' @examples
#' data <- tidy_plates
#' # 0.5 is unreasonable in most uses, but is used here to ensure some output
#' suspicious_plate_id <- qc_raw_extr(data, max_coeff = 0.5,
#'     suppress_message = TRUE, suppress_warning = TRUE)
#' suspicious_extr <- suspicious_extr(data, max_coeff = 0.5,
#'     suspicious_plate_id = suspicious_plate_id)
#' multiplot_outlier_extr(suspicious_extractant = suspicious_extr, max_coeff = 0.5)
#' ## Tip: if too many curves appear, consider cutting `suspicious_extractant`
#' ##.     into several subsets, to be given as input for multiple runs of `multiplot_outlier_extr()`
multiplot_outlier_extr <- function(
    suspicious_extractant = NULL,
    data = NULL, # must be provided if suspicious_extractant is NULL
    max_coeff = 5

){
  if (is.null(suspicious_extractant)) {
    suspicious_extractant <- suspicious_extr(data, max_coeff = max_coeff)
  }

  plots <- suspicious_extractant |>
    dplyr::group_map(
      .f = ~ggplot2::ggplot(.x, ggplot2::aes(x = abs)) +
        ggplot2::geom_histogram() +
        ggplot2::theme_minimal() +
        ggplot2::labs(title = .y)
    )

  multiple_plot <- patchwork::wrap_plots(plots, axis_titles = "collect") +
    patchwork::plot_annotation(title = "Distribution of absorbance of extractant",
                               subtitle = paste0(
                                 "Only displays plates for which the coefficient of variation\nfor the extractant is above ",
                                 max_coeff)
    )

  return(multiple_plot)
}


utils::globalVariables(c("abs", "plate_id", "dataset", "well_id"))
#' Identify outlier-wells within plates containing suspicious extractant data
#'
#' @param suspicious_extractant A tibble as generated by `suspicious_extr()`,
#'     can be computed from `data` with `suspicious_extr()`
#' @param data Defaults to NULL. If provided, must be a tibble formatted as `tidy_plates`
#' @param max_coeff User-defined threshold value, defaults at 5%. All plates for which
#'     the coefficient of variation for extractant raw absorbance is above this threshold
#'     will be considered "suspicious plates". ! Be consistent with previous steps
#'
#' @import ggplot2
#' @importFrom forcats fct_rev
#' @importFrom ggrepel geom_text_repel
#'
#'
#' @returns A boxplot generated by ggplot, highlighting information necessary to
#'     create a tibble of wells to be removed with `remove_wells()`, i.e.,
#'     for each boxplot: plate_ids, well_ids and plate number (corresponding to
#'     the order of plate ids in `suspicious_extractant`)
#' @export
#'
#' @examples
#' data <- tidy_plates
#' # 0.5 is unreasonable in most uses, but is used here to ensure some output
#' suspicious_plate_id <- qc_raw_extr(
#'    data, max_coeff = 0.5, suppress_message = TRUE, suppress_warning = TRUE)
#' suspicious_extr <- suspicious_extr(
#'    data, max_coeff = 0.5, suspicious_plate_id = suspicious_plate_id)
#' boxplot_outlier_extr(
#'     suspicious_extractant = suspicious_extr,
#'     max_coeff = 0.5)
boxplot_outlier_extr <- function(
    suspicious_extractant = NULL,
    data = NULL, # must be provided if suspicious_extractant is NULL
    max_coeff = 5
) {

  # n_row_panels <- suspicious_extractant |>
  #   ungroup() |>
  #   select(dataset) |>
  #   unique() |>
  #   nrow()

  nb_plates <- suspicious_extractant |>
    ungroup() |>
    select(dataset, plate_id) |>
    unique() |>
    nrow()

  boxplot <- suspicious_extractant |>
    ggplot2::ggplot(ggplot2::aes(x = abs, y = forcats::fct_rev(plate_id))) +
    ggplot2::theme_minimal() +
    ggplot2::geom_boxplot(
      fill = "grey90", color = "grey70",
      outliers = FALSE,
      # outlier.colour = "grey50",
      # outlier.fill = "grey50",
      # outlier.alpha = 0.6#,
      #outlier.shape = 1
    ) +
    ggplot2::geom_jitter(colour = "grey30", alpha = 0.7, shape = 1, height = 0.1) +
    ggrepel::geom_text_repel(ggplot2::aes(label = well_id), colour = "purple", alpha = 1, min.segment.length = 1) +
    ggplot2::annotate(
      geom = "text",
      y = (0.1 + seq(1, nb_plates)), x = 0,
      label = paste0("plate ", seq(nb_plates, 1)),
      hjust = 0,
      colour = "grey20") +
    # ggplot2::geom_text(
    #   ggplot2::aes(label = well_id), colour = "purple", alpha = 1,
    #   check_overlap = TRUE,
    #   position = ggplot2::position_jitter(height = 0.4, width = 0), size = 3
    #  ) +
    #facet_wrap(~dataset, scales = "free", nrow = n_row_panels) +
    ggplot2::ylab("Plate id") + ggplot2::xlab("raw absorbance of extractant wells") +
    ggplot2::labs(title = "Identifying outliers for extractant wells",
         subtitle = paste0("Only plates with outliers are displayed here\n(coefficient of variation of absorbance > ", max_coeff, ")")) #+
  #coord_flip()

  return(boxplot)

}

